### ISSUE TITLE
Cannot be used for the Beat Saber Beatogether PC version

### ISSUE THREAD

**Issue by alsdzx** [rcelyte/BeatUpRcelyte#30] opened 2024-11-08 16:37 UTC
The Quest version Beatogether v2.2.0 works well,but can't be used for the PC Beatogether v2.2.0

master.c] Unhandled property [Unreliable]
[master.c] disconnect [::ffff:58.21.70.152]:46802
[internal.c] (HTTP,game): GET /?access_token=OC%7C5053788584737329%7C&service_environment=ProductionB
[internal.c] (HTTP,game): GET /mp_override.json?access_token=OC%7C5053788584737329%7C&service_environment=ProductionB
[internal.c] (HTTP,game): POST /beat_saber_get_multiplayer_instance
[internal.c] TODO: parse songPackMask
[pool.c] 1 room open
[instance.c] opening room (0,0)
[instance.c] state (none) -> Lobby.Idle
[instance.c] resolve  | player slots (1/5): [⠁]
[master_local.c] Sending player to room 'SJRR4'
[internal.c] TODO: encode songPackMask
[master.c] connect [::ffff:58.21.70.152]:54597
[net.c] Packet decryption failed
[instance.c] session timeout
[instance.c] disconnect AF_UNSPEC | player slots (0/5): [⠀]
[instance.c] closing room (0,0)
[pool.c] 0 rooms open

**Comment by alsdzx** [comment] 2024-11-08 16:40
I didn't use SSL

**Comment by rcelyte** [comment] 2024-11-09 08:42
What do your BeatTogether configs contain on PC vs Quest?

**Comment by alsdzx** [comment] 2024-11-09 08:50
The PC config copy from Quest

**Comment by rcelyte** [comment] 2024-11-09 08:51
Can you paste the full text either here or in Discord DMs?

**Comment by alsdzx** [comment] 2024-11-09 08:52
But the config will change when I start the PC game

**Comment by alsdzx** [comment] 2024-11-09 08:52
{"SelectedServer":"BSS","Servers":[{"ServerName":"BSS","ApiUrl":"http://139.196.158.159:28889","StatusUri":"http://139.196.158.159:28889","MaxPartySize":10,"DisableSsl":true},{"ServerName":"BeatTogether","ApiUrl":"http://master.beattogether.systems:8989","StatusUri":"http://master.beattogether.systems/status","MaxPartySize":10,"DisableSsl":true}]}

**Comment by rcelyte** [comment] 2024-11-09 08:54
Does joining with `"DisableSsl": false` work?

**Comment by alsdzx** [comment] 2024-11-09 08:57
PC BeatTogether.json：

{
  "SelectedServer": "BSS",
  "Servers": [
    {
      "ServerName": "BeatTogether",
      "HostName": "master.beattogether.systems",
      "ApiUrl": "http://master.beattogether.systems:8989",
      "StatusUri": "http://master.beattogether.systems/status",
      "MaxPartySize": 10,
      "DisableSsl": true
    },
    {
      "ServerName": "BSS",
      "HostName": "",
      "ApiUrl": "http://139.196.158.159:28889",
      "StatusUri": "http://139.196.158.159:28889",
      "MaxPartySize": 10,
      "DisableSsl": true
    }
  ]
}

**Comment by alsdzx** [comment] 2024-11-09 08:57
> Does joining with `"DisableSsl": false` work?
No,it not work

**Comment by rcelyte** [comment] 2024-11-09 09:02
Try adding this to `Servers` and seeing if that connects:
```json
{"ServerName":"battletrains.org","ApiUrl":"https://status.master.battletrains.org","StatusUri":"https://status.master.battletrains.org","MaxPartySize":10,"DisableSsl":false}
```

**Comment by alsdzx** [comment] 2024-11-09 09:06
PC Beatogether will automatically add ”Hostname“

**Comment by alsdzx** [comment] 2024-11-09 09:06
CFR-5

**Comment by alsdzx** [comment] 2024-11-09 09:09
> Try adding this to `Servers` and seeing if that connects:
> 
> ```json
> {"ServerName":"battletrains.org","ApiUrl":"https://status.master.battletrains.org","StatusUri":"https://status.master.battletrains.org","MaxPartySize":10,"DisableSsl":false}
> ```

Could not connect to the server.
Server dose not exist(CFR-5)

**Comment by rcelyte** [comment] 2024-11-09 09:54
Okay so apparently BeatTogether's `DisableSsl` option is a lie and gets overridden during the 'Checking Server Status' spinner :skull:

**Comment by rcelyte** [comment] 2024-11-09 10:52
Looks like the fault here lies with MultiplayerCore. I'll leave this issue open until https://github.com/Goobwabber/MultiplayerCore/pull/56 gets merged.

**Comment by rcelyte** [comment] 2024-11-11 22:32
@alsdzx Can you confirm that this issue is resolved with https://github.com/Goobwabber/MultiplayerCore/releases/tag/v1.5.4 ?

**Comment by lyyQwQ** [comment] 2024-11-12 08:31
> @alsdzx Can you confirm that this issue is resolved with https://github.com/Goobwabber/MultiplayerCore/releases/tag/v1.5.4 ?

I used version 1.37.1 and encountered this problem. I referred to the PR you submitted, downloaded and modified the source code of MultiplayerCore, and compiled version 1.37.1. Now the problem is solved.

**Comment by lyyQwQ** [comment] 2024-11-12 08:35
I also found an interesting phenomenon. I set DisableSsl to true in the configuration file, but after starting the game, it still changes to false. However, the issue of being unable to connect due to SSL has not occurred again. I didn't closely examine the relevant part of the code; maybe there is also a problem with the code that edits the configuration file?

**Comment by alsdzx** [comment] 2024-11-12 08:42
> @alsdzx Can you confirm that this issue is resolved with https://github.com/Goobwabber/MultiplayerCore/releases/tag/v1.5.4 ?

it works well

**Comment by rcelyte** [comment] 2024-11-12 09:03
Great!

> I set DisableSsl to true in the configuration file, but after starting the game, it still changes to false

As I mentioned, BeatTogether overrides that setting if the server specifies a preference.

**Closed by rcelyte** 2024-11-12 09:03 UTC
